# Site settings
title: Getting started
email: vince.delia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My notes on getting started with the stuff I love
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vdelia.github.io" # the base hostname & protocol for your site
github_username:  vdelia

# Build settings
markdown: kramdown
